-- CREATE TABLE
--     IF NOT EXISTS lexon.machine_states_history (
--         id TEXT PRIMARY KEY NOT NULL,
--         machine_instance_id TEXT NOT NULL REFERENCES lexon.machine_instances (id) ON DELETE CASCADE,
--         state_id TEXT NOT NULL REFERENCES lexon.machine_states (id) ON DELETE CASCADE,
--         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--     );
