version: "3.8"
services:
  db:
    image: postgres:16-alpine
    container_name: lexon_engine_test_db
    environment:
      POSTGRES_DB: lexon_engine_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d lexon_engine_test_db"]
      interval: 5s
      timeout: 5s
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: lexon_engine_test_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admin:secretpassword@db:5432/lexon_engine_test_db?sslmode=disable
    volumes:
      - .:/app
    # command: ["go", "test", "./..."]

volumes:
  pgdata:
